import 'package:flutter/material.dart';
import 'package:uas/chatbot.dart';
import 'package:uas/menukamera.dart';
import 'package:uas/service/prediksi_sevice.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class halamanhome extends StatelessWidget {
  const halamanhome({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          HalamanHome(),
        ]),
      ),
    );
  }
}

class HalamanHome extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 237,
                top: -128,
                child: Opacity(
                  opacity: 0.50,
                  child: Container(
                    width: 238,
                    height: 225,
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 26,
                          child: Container(
                            width: 199,
                            height: 199,
                            decoration: ShapeDecoration(
                              color: Color(0x60009873),
                              shape: OvalBorder(),
                            ),
                          ),
                        ),
                        Positioned(
                          left: 39,
                          top: 0,
                          child: Container(
                            width: 199,
                            height: 199,
                            decoration: ShapeDecoration(
                              color: Color(0x99009873),
                              shape: OvalBorder(),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 84,
                top: 114,
                child: Text(
                  'Search Doctor',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black.withOpacity(0.4399999976158142),
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 175,
                child: SizedBox(
                  width: 132,
                  height: 31,
                  child: Text(
                    'Doctors',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 30,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 244,
                child: SizedBox(
                  width: 132,
                  height: 31,
                  child: Text(
                    'Kanker Mulut',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 18,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 299,
                top: 17,
                child: Container(
                  width: 43,
                  height: 43,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/43x43"),
                      fit: BoxFit.fill,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 361,
                child: Container(
                  width: 155,
                  height: 137,
                  decoration: ShapeDecoration(
                    color: Color(0xFF019874),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x28000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 2,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 474,
                child: Container(
                  width: 200,
                  height: 105,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x28000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 2,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 593,
                child: Container(
                  width: 334,
                  height: 129,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x28000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 2,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 488,
                child: SizedBox(
                  width: 189,
                  height: 28,
                  child: Text(
                    'Dr. Mosia Gloria',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 18,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 510,
                child: Text(
                  'Sr. Psychologist',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black.withOpacity(0.5899999737739563),
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 254,
                top: 466,
                child: Container(
                  width: 164,
                  height: 86,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x28000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 2,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 261,
                top: 363,
                child: Opacity(
                  opacity: 0.60,
                  child: Container(
                    width: 109,
                    height: 112,
                    decoration: ShapeDecoration(
                      color: Color(0xFF019874),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(10),
                      ),
                      shadows: [
                        BoxShadow(
                          color: Color(0x28000000),
                          blurRadius: 10,
                          offset: Offset(0, 4),
                          spreadRadius: 2,
                        )
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 299,
                child: Container(
                  width: 174,
                  height: 175,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("assets/doktor1.jpeg/174x175"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 248,
                top: 337,
                child: Opacity(
                  opacity: 0.60,
                  child: Container(
                    width: 107,
                    height: 138,
                    decoration: BoxDecoration(
                      image: DecorationImage(
                        image: NetworkImage("https://via.placeholder.com/107x138"),
                        fit: BoxFit.fill,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 254,
                top: 496,
                child: SizedBox(
                  width: 139,
                  height: 19,
                  child: Opacity(
                    opacity: 0.60,
                    child: Text(
                      'Sr. Psychologist',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.black.withOpacity(0.5899999737739563),
                        fontSize: 12,
                        fontFamily: 'Poppins',
                        fontWeight: FontWeight.w400,
                        height: 0,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 254,
                top: 479,
                child: SizedBox(
                  width: 156,
                  height: 23,
                  child: Opacity(
                    opacity: 0.60,
                    child: Text(
                      'Dr. Margret Dina',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 13,
                        fontFamily: 'Poppins',
                        fontWeight: FontWeight.w700,
                        height: 0,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 208,
                top: 619,
                child: Container(
                  width: 128,
                  height: 91,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 36.62,
                        top: 21.47,
                        child: Opacity(
                          opacity: 0.10,
                          child: Container(
                            width: 10.48,
                            child: Stack(children: [
                            
                            ]),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 609,
                child: Text(
                  'Instant Appointment \n',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 632,
                child: SizedBox(
                  width: 170,
                  height: 96,
                  child: Text(
                    'Lorem ipsum dolor sit amet, consectetur.',
                    style: TextStyle(
                      color: Colors.black.withOpacity(0.6299999952316284),
                      fontSize: 15,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 104,
                child: Container(
                  width: 311,
                  height: 42,
                  decoration: ShapeDecoration(
                    color: Color(0x3D737977),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                ),
              ),
               Positioned(
                left: 29,
                top: 715,
                width: 340,
                height: 70,
                child: Container(
                  decoration: ShapeDecoration(
                    color: Color(0xFF019773),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                  child: ElevatedButton(
                    onPressed: () {
                      Navigator.push(
                        context,  
                        MaterialPageRoute(builder: (context) => PredictView()),
                      );
                    }, 
                    style: ElevatedButton.styleFrom(
                      primary: const Color.fromARGB(255, 1, 151, 115),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                    ),
                    child: SizedBox(
                      width: 169,
                      height: 43,
                      child: Text(
                        'Mulai analisa',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 24,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 3,
                top: 676,
                child: Container(
                  width: 170,
                  height: 99,
                  child: Stack(
                    children: [
                      Positioned(
                left: 33,
                top: 0,
                width: 105,
                height: 32,
                child: Container(
                  decoration: ShapeDecoration(
                    color: Color(0xFF017C97),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                  child: ElevatedButton(
                    onPressed: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (context) => chatbot()),
                      );
                    },
                    style: ElevatedButton.styleFrom(
                      primary: const Color.fromARGB(255, 1, 151, 115),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                    ),
                    child: SizedBox(
                      width: 170,
                      height: 82,
                      child: Text(
                        'Chatbot',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 15,
                          fontFamily: 'Roboto',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}